---

# file: copy-root-ca-to-cache.yml

- name: exec copy-root-ca-to-cache
  block:
    - name: prompt exec coyp-root-ca-to-cache notified
      debug: 
        msg: "notified -> start copy root ca-config, ca-pem, ca-key.pem to remote cache ..."

#   copy ca-config.json from /etc/cert-cache/ca-config to /etc/cert-cache/kubernetes
#   copy ca.pem, ca-key.pem in /etc/cert-cache/ca to /etc/cert-cache/kubernertes
#     
#   . first fetch from remote to ansible temp directory and copy to remote
#

#     ca-config.json
# and
#     root-to-intermediate-ca-config.json for intermediate-CA (and front-proxy-client-ca for metrics-server) config

    - name: fetch root ca-config.json and intermediate-CA config to ansible temp dir
      fetch:
        src: "{{ cert_cache_path_ca_config }}/{{ item }}"
        dest:  "{{ dep_path_tmp_exchange }}/"
        flat: true
      with_items:
        - ca-config.json
        - root-to-intermediate-ca-config.json
    - name: copy root ca-config.json and intermediate-CA config to kube cache
      copy:
        src: "{{ dep_path_tmp_exchange }}/{{ item }}"
        dest: "{{ cert_cache_path_kubernetes }}/"
      with_items:
        - ca-config.json
        - root-to-intermediate-ca-config.json

#   ca.pem, ca-key.pem
# and
#   front-proxy-client-ca.pem, front-proxy-client-ca-key.pem

    - name: fetch root-CA cert and intermediate-CA(also front-proxy-client-ca) to ansible temp dir
      fetch:
        src: "{{ cert_cache_path_ca }}/{{ item }}"
        dest:  "{{ dep_path_tmp_exchange }}/"
        flat: true
      with_items:
        - ca.pem
        - ca-key.pem
        - front-proxy-client-ca.pem
        - front-proxy-client-ca-key.pem
    - name: copy root-CA cert and intermediate-CA cert (also as front-proxy-client-ca) to kube cache
      copy:
        src: "{{ dep_path_tmp_exchange }}/{{ item }}"
        dest: "{{ cert_cache_path_kubernetes }}/"
      with_items:
        - ca.pem
        - ca-key.pem
        - front-proxy-client-ca.pem
        - front-proxy-client-ca-key.pem

  rescue:
    - debug:
        msg: "issue occured in exec copy-root-ca-to-cache (to kube cache))"

  always:
    - debug:
        msg: ". exit exec copy-root-ca-to-cache.yml (to kube cache))"
