---

# file: roles/gen-kube-ca-cert/tasks/main.yml

- name: traceing in gen-kube-ca-cert/task/main.yml
  debug:
    msg: "check tracing - starting gen-kube-ca-cert task main"
  run_once: true
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

- name: schedule exec generating kube ca cert
  import_tasks: schedule-gen-kube-ca.yml
  run_once: true
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

