---

# file: deploy-metrics-server-pod.yml
#

# deploy kube metrics-server pod using yaml 

# create metrics-server pod
- name: create metrics-server pod
  command: "{{ bin_path }}/kubectl create -f {{ metrics_server_yaml_path }}/metrics-server.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"
