---

# file: create-kube-apiserver-systemd-file.yml
#
#### generate kubernetes systemd service files for:
#  * 1. apiserver service
#    2. controller-manager service
#    3. scheduler service
#
  
- name: exec create-kube-apiserver-systemd-file
  template: 
    src: kube-core/apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
