---

# file: create-kube-scheduler-systemd-file.yml
#

#### generate kubernetes systemd service files for:
#    1. apiserver service
#    2. controller-manager service
#  * 3. scheduler service
#
  
- name: exec create-kube-scheduler-systemd-file
  template:
    src: kube-core/scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    
