---

# playbook - test.yml
#

- hosts: kube-nodes

  roles:
    - { role: cluster-defaults }

  tasks:
#
    - include_vars:
        file: roles/create-kube-worker-node/defaults/main.yml

    - name: test
      include: roles/create-kube-worker-node/tasks/schedule-test.yml

