---

# playbook - gen-kube-ca-cert.yml
#

# only use this playbook for node-0 of cluster masters
# attention: only for node-0 of cluster masters

- hosts: node1
  become: yes
  roles:
    - { role: gen-kube-ca-cert }
