---

# file: gen-root-kube-etcd-ca-cert.yml

# func: 
#     (rem: need generate in sequence)
#
#   generate root ca cert
#   generate kube ca cert
#   generate etcd ca cert

# only use this playbook for node-0 of cluster masters
# attention: only for node-0 of cluster masters

- hosts: node1
  become: yes
  roles:
    - { role: gen-root-ca-cert }

# only use this playbook for node-0 of cluster masters
# attention: only for node-0 of cluster masters

- hosts: node1
  become: yes
  roles:
    - { role: gen-kube-ca-cert }

# only use this playbook for node-0 of cluster masters
# attention: only for node-0 of cluster masters

- hosts: node1
  become: yes
  roles:
    - { role: gen-etcd-ca-cert }



