---

# file: roles/cluster-defaults/defaults/cert-backup-path.yml

# definition of directory to store cert files on ansible deploy site 
#   works as: 
#     1. backup; 
#     2. source file for deployment
#   directory: dep-data/cert-local/<item_directory_name>
#

# --------------------
# cert backup path (on ansible deploy site)
#

# {{ dep_path_backup_cert }} - dep-data/cert-local


# path for ca-config
cert_backup_path_ca_config: "{{ dep_path_backup_cert }}/ca-config"

# path for root ca
cert_backup_path_ca: "{{ dep_path_backup_cert }}/ca"

# path for intermediate-ca config
cert_backup_path_intermediate_ca_config: "{{ dep_path_backup_cert }}/intermediate-ca-config"

# path for intermediate-ca
cert_backup_path_intermediate_ca: "{{ dep_path_backup_cert }}/intermediate-ca"

# path for admin ( admin account of kubectl client)
cert_backup_path_kube_admin: "{{ dep_path_backup_cert }}/kube-admin"

# path for etcd cluster
cert_backup_path_etcd: "{{ dep_path_backup_cert }}/etcd"

# path for flannel daemon
cert_backup_path_flanneld: "{{ dep_path_backup_cert }}/flanneld"

# path for kubernetes cert
cert_backup_path_kubernetes: "{{ dep_path_backup_cert }}/kubernetes"

# path for kube apiserver cert
cert_backup_path_kube_apiserver: "{{ dep_path_backup_cert }}/kube-apiserver"

# path for kube controller-manager cert
cert_backup_path_kube_controller_manager: "{{ dep_path_backup_cert }}/kube-controller-manager"

# path for kube scheduler cert
cert_backup_path_kube_scheduler: "{{ dep_path_backup_cert }}/kube-scheduler"

# path for kube proxy cert
cert_backup_path_kube_proxy: "{{ dep_path_backup_cert }}/kube-proxy"

# path for kube service account cert ( sa - service account )
cert_backup_path_kube_serviceaccount: "{{ dep_path_backup_cert }}/kube-serviceaccount"

# path for kubelet cert (server and client cert), every node has it sub dire
cert_backup_path_kubelet: "{{ dep_path_backup_cert }}/kubelet"


### kube front proxy (aggregator) client cert

# path for front proxy client ca config backup
cert_backup_path_kube_front_proxy_client_ca_config: "{{ dep_path_backup_cert }}/front-proxy-client-ca-config"

# path for front proxy client ca backup
cert_backup_path_kube_front_proxy_client_ca: "{{ dep_path_backup_cert }}/front-proxy-client-ca"

# path for front proxy client cert backup 
cert_backup_path_kube_front_proxy_client: "{{ dep_path_backup_cert }}/front-proxy-client"

# path for metrics-server server cert backup
cert_backup_path_kube_metrics_server: "{{ dep_path_backup_cert }}/kube-metrics-server"

# path for aggregated-apiserver-client client cert
cert_backup_path_kube_aggregated_apiserver_client: "{{ dep_path_backup_cert }}/kube-aggregated-apiserver-client"


