---

# file: deploy-coredns-service.yml
#

# deploy coredns service using yaml ( one pod + another replicated pod )

# create coredns yaml 
- name: create coredns service file ( yaml )
  template:
    src: coredns.yaml.j2
    dest: "{{ kube_yaml_config_path }}/coredns.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

# create coredns service
- name: create coredns pod and service
  command: "{{ bin_path }}/kubectl create -f {{ kube_yaml_config_path }}/coredns.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"
