---

# file: deploy-coredns-service.yml
#

# deploy coredns service using yaml ( one coredns pod + dns auto-scaler )


# create coredns service pod
- name: create coredns pod and service
  command: "{{ bin_path }}/kubectl create -f {{ kube_coredns_path }}/coredns.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

# create dns auto-scaler pod deployment
- name: create dns autoscaler pod deployment
  command: "{{ bin_path }}/kubectl create -f {{ kube_coredns_path }}/dns-horizontal-autoscaler.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

