---

# file: enable-and-start-docker-service.yml

- debug:
    msg: "Starting DOCKER service on node - {{ inventory_hostname }} ..."

# enable and start docker service
- name: enable and start docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

#- block:
#    - name: remove docker0 interface
#      command: ip link delete docker0
#  rescue:
#    - debug:
#        msg: "ERROR: fail to delete docker0 interface. please check."
## end block

