---

# file: create-kube-worker-node-cert-files.yml
#
#  func: 
#    copy cert files for kube worker node from cert-cache
#

# copy ca/cert to worker node from cert cach directory
# -
# fech from cert cache on ansible to temp on ansible
# copy from tem on ansible to worker node to deploy to
#

# 1.
#   kube root ca cert
# fech kube root ca/cert to ansible temp exchange dir
- name: fetch root ca cert from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_ca }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - ca.pem
    - ca-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"
# ??? do not add ca-key.pem on worker node

# copy kube root ca cert from ansible temp exchange directory to kube worker node
- name: copy root ca cert files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - ca.pem
    - ca-key.pem

#### CHECK - if need add admin client and cert on worker node
# 2.
#   kube admin cert key
# fech kube admin cert key to ansible temp exchange dir
- name: fetch kube admin cert key from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_admin }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - kube-admin.pem
    - kube-admin-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube admin cert key from ansible temp exchange directory to kube work node
- name: copy kube admin cert key files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - kube-admin.pem
    - kube-admin-key.pem

# 3.
#   kube proxy cert key
# fech kube proxy cert key to ansible temp exchange dir
- name: fetch kube proxy cert key from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_proxy }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - kube-proxy.pem
    - kube-proxy-key.pem
    - timestamp.log
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube proxy cert key from ansible temp exchange directory to kube worker node
- name: copy kube proxy cert key files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - kube-proxy.pem
    - kube-proxy-key.pem
    - timestamp.log

# 4.
#   kube-apiserver-client file
#   remar: bootstrap token secret yaml file is generated by worker node to update expiration
# fech kubelet bootstrap token to ansible temp exchange dir
- name: fetch kubelet bootstrap token from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_apiserver }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - token.csv
    - kube-apiserver-client.pem
    - kube-apiserver-client-key.pem
    - kube-apiserver.pem
    - kube-apiserver-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube admin cert key from ansible temp exchange directory to kube work node
- name: copy kube admin cert key files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - token.csv
    - kube-apiserver-client.pem
    - kube-apiserver-client-key.pem
    - kube-apiserver.pem
    - kube-apiserver-key.pem

#############
#############
#############

# 5.
#   kube front proxy client cert
# fech kube front proxy client cert to ansible temp exchange dir
- name: fetch kube front proxy client cert key from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_front_proxy_client }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - front-proxy-client-ca.pem
    - front-proxy-client-ca-key.pem
    - front-proxy-client.pem
    - front-proxy-client-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube proxy cert key from ansible temp exchange directory to kube cluster master
- name: copy kube proxy cert key files to kube master
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - front-proxy-client-ca.pem
    - front-proxy-client-ca-key.pem
    - front-proxy-client.pem
    - front-proxy-client-key.pem


##############
##############
##############

# 6.
#   kube-metrics-server server cert
# fech kube-metrics-server cert to ansible temp exchange dir
- name: fetch kube-metrics-server cert from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_metrics_server }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - kube-metrics-server.pem
    - kube-metrics-server-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube admin cert key from ansible temp exchange directory to kube work node
- name: copy kube admin cert key files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - kube-metrics-server.pem
    - kube-metrics-server-key.pem


# 7.
#   kube-aggregated-apiserver-client file
# fech kube-appregated-apiserver-client to ansible temp exchange dir
- name: fetch kube-aggregated-apiserver-client from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_aggregated_apiserver_client }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - kube-aggregated-apiserver-client.pem
    - kube-aggregated-apiserver-client-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube-aggregated-apiserver-client from ansible temp exchange directory to kube work node
- name: copy kube aggregated apiserver client cert key files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - kube-aggregated-apiserver-client.pem
    - kube-aggregated-apiserver-client-key.pem


#############
#############
#############


#############################
# CHECK - if need to install serviceaccount cert on worker node

# 8.
#   kube serviceaccount cert key
# fech kube serviceaccount cert key to ansible temp exchange dir
- name: fetch kube serviceaccount cert key from cache dir to temp
  fetch:
    src: "{{ cert_cache_path_kube_serviceaccount }}/{{ item }}"
    dest: "{{ dep_path_tmp_exchange }}/"
    flat: true
  with_items:
    - kube-serviceaccount.pem
    - kube-serviceaccount-key.pem
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

# copy kube serviceaccount cert key from ansible temp exchange directory to kube worker node
- name: copy kube serviceaccount cert key files to kube worker node
  copy:
    src: "{{ dep_path_tmp_exchange }}/{{ item }}"
    dest: "{{ kube_cert_path }}/"
    owner: "{{ kube_user }}"
    group: "{{ kube_group }}"
    mode: 0640
  with_items:
    - kube-serviceaccount.pem
    - kube-serviceaccount-key.pem

