---

# file: roles/create-etcd-cluster/tasks/main.yml

# include variable - using in create-etcd-cluster role
- block:
  - debug:
      msg: "include default variables ..."
  - name: INCLUDE VAR main.yml (in dir roles/create-etcd-cluster/defaults)
    include_vars:
#   relative directory - relative to roles/roles-item/
      file: ../create-etcd-cluster/defaults/main.yml
# end block

# deploy etcd cluster node
- block:
  - name: exec schedule-create-etcd-node
    import_tasks: schedule-create-etcd-node.yml
  - name: reboot etcd cluster node to make etcd clude node and cert take effect
    reboot:
  rescue:
    - debug: "error occured in creating etcd cluster node: {{ inventory_hostname }}."
# end block
  when:
    - inventory_hostname in groups['etcd-nodes']

