---

# file: roles/gen-etcd-ca-cert/tasks/main.yml

- name: traceing in gen-etcd-ca-cert/task/main.yml
  debug:
    msg: "check tracing - starting gen-etcd-ca-cert task main"
  run_once: true
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

- name: schedule exec generating etcd ca cert
  import_tasks: schedule-gen-etcd-ca.yml
  run_once: true
  delegate_to: "{{ groups['ansible-node'][0] }}"

