---

# file: roles/os-enable-ipvs/tasks/install-ipset-n-ipvsadm.yml
#

# . install ipset
# . install ipvsadm
#

# install ipset and ipvsadm before enable ipvs
- name: block - install ipset and ipvsadm

  block:
    - name: install ipset and ipvsadm
      yum:
        name: ['ipset', 'ipvsadm', 'bridge-utils']
        state: present

  always:
    - name: ipset and ipvsadm installed
      debug:
        msg: ' ipset, ipvsadm and bridge-utils installed.  '
