---

# file: install-network-utility.yml

- name: install epel repository
  yum:
    name: ['epel-release']
    state: latest

# install network utilities
#
# revision:
# . bridge-utils not available on centos 8, replaced by networkmanager command nmcli
# . iptables package replaced by iptables-services
#
- name: install network utility
  yum:
    #name: ['iproute', 'net-tools', 'bind-utils', 'iptables', 'bridge-utils', 'wget', 'jq', 'htop', 'nmap-ncat.x86_64']
    name: ['iproute', 'net-tools', 'bind-utils', 'iptables-services', 'dnsmasq', 'wget', 'jq', 'htop', 'nmap-ncat.x86_64']
    state: latest




