---

# file: install-default-iptalbes-file.yml

#
- name: 
  template:
    src: ../../cluster-defaults/templates/iptables-direct-master-node-conf.j2
    dest: /etc/sysconfig/iptables-master-node.backup
- name:
  template:
    src: ../../cluster-defaults/templates/iptables-direct-worker-node-conf.j2
    dest: /etc/sysconfig/iptables-worker-node.backup
- name:
  template:
    src: ../../cluster-defaults/templates/iptables-direct-etcd-node-conf.j2
    dest: /etc/sysconfig/iptables-etcd-node.backup

- name:
  template:
    src: ../../cluster-defaults/templates/iptables-direct-master-node-conf.j2
    dest: /etc/sysconfig/iptables






