---

# file: install-network-utility.yml

# install network utilities
#
- name: install network utility
  yum:
    name: ['iproute', 'net-tools', 'bind-utils', 'iptables', 'bridge-utils', 'wget', 'jq']
    state: latest




