---

# file: roles/os-enable-ipvs/tasks/install-ipset-n-ipvsadm.yml
#

# . install ipset
# . install ipvsadm
# . install bridge-utils (brctl command) 
#
# revision:
# . (ipset not need to install on centos8 - it is default on centos8, not ipset package available now)
# . (bridge-utils package is deprecated on centos8, and there is no bridge-utils package available for centos8.
#    use networkmanger command line nmcli command to access bridge )

# install ipset and ipvsadm before enable ipvs
- name: block - install ipset and ipvsadm

  block:
    - name: install ipset and ipvsadm
      yum:
        # name: ['ipset', 'ipvsadm', 'bridge-utils']
        name: ['ipvsadm']
        state: present

  always:
    - name: ipset and ipvsadm installed
      debug:
        # msg: ' ipset, ipvsadm and bridge-utils installed.  '
        msg: ' ipvsadm installed.  '
