---

# file: deploy-hostnames-pod.yml
#

# deploy 3 hostnames pods using yaml - for test only

# create hostnames yaml 
- name: create hostnames file ( yaml )
  template:
    src: hostnames.yaml.j2
    dest: "{{ kube_yaml_config_path }}/hostnames.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"

# create hostnames pod
- name: create hostnames pod
  command: "{{ bin_path }}/kubectl create -f {{ kube_yaml_config_path }}/hostnames.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-masters'][0] }}"
