---

# file: remove-create-kube-worker-node-ex.yml
#

# func:
#   general: remove generated create-kube-worker-node procedure
#     1. remove remote /etc/kubernetes directory
#     2. remove remote /etc/etcd directory
#


# remove kube config and etcd config dirs on cluster master
- block:
    - name: stop services 1 - kubelet service if exist
      systemd:
        name: kubelet
        daemon_reload: no
        state: stopped
        enabled: no
    - name: remove systemd file
      file:
        path: /etc/systemd/system/kubelet.service
        state: absent
  rescue:
    - debug: 
        msg: "ERROR: can not stop kubelet service, or kubelet service not exist"
# end block
  when:
    - inventory_hostname in groups['kube-nodes']

#- block:
#    - name: stop services 2 - kube-proxy service if exist
#      systemd:
#        name: kube-proxy 
#        daemon_reload: no
#        state: stopped
#        enabled: no
#    - name: remove systemd file
#      file:
#        path: /etc/systemd/system/kube-proxy.service
#        state: absent
#  rescue:
#    - debug:
#        msg: "ERROR: can not stop kube-proxy service, or kube-proxy service not exist"
## end block
#  when:
#    - inventory_hostname in groups['kube-nodes']

- block:
    - name: stop services 3 - docker service if exist
      systemd:
        name: docker
        daemon_reload: no
        state: stopped
        enabled: no
#    - name: remove systemd file
#      file:
#        path: /etc/systemd/system/docker.service
#        state: absent
  rescue:
    - debug:
        msg: "ERROR: can not stop docker service, or docker service not exist"
# end block
  when:
    - inventory_hostname in groups['kube-nodes']

#- block:
#    - name: stop services 4 - flannel service if exist
#      systemd:
#        name: flannel
#        daemon_reload: no
#        state: stopped
#        enabled: no
#  rescue:
#    - debug:
#        msg: "ERROR: can not stop flannel service, or flannel service not exist"
## end block
#  when:
#    - inventory_hostname in groups['kube-nodes']

#- block:
#    - name: stop services 5 - calico-node-container service if exist
#      systemd:
#        name: calico-node-container
#        daemon_reload: no
#        state: stopped
#        enabled: no
#  rescue:
#    - debug:
#        msg: "ERROR: can not stop calico-node-container service, or calico-node-container service not exist"
## end block
#  when:
#    - inventory_hostname in groups['kube-nodes']

- block:
    - name: remove docker-ce package
      yum:
        name: docker-ce
        state: absent
#        autoremove: yes
  rescue:
    - debug:
        msg: "ERROR: can not remove docker-ce package, or docker-ce package not exist"
#     end block
  when:
    - inventory_hostname in groups['kube-nodes']


- block:
    - name: remove kube and etcd config and data directories on worker node
      file:
        path: "{{ item }}"
        state: absent
        force: yes
      with_items:
        - "{{ kube_config_path }}/cert/"
        - "{{ kube_config_path }}/"
        - "{{ etcd_config_path }}/"
#        - "{{ docker_config_path }}/"
#        - "{{ flannel_cert_path }}/"
#        - "{{ flannel_config_path }}/"
        - "{{ cni_config_path }}/"
        - "{{ etcd_data_path }}/"
        - "{{ kube_data_path }}/"
        - "{{ kube_proxy_data_path }}/"
#        - "{{ docker_data_path }}/"
        - "{{ cni_data_path }}/"
#        - "{{ calico_log_path }}/"
#        - "{{ calico_data_path }}/"
#        - "{{ calico_config_conf_path }}/"
#        - "{{ calico_config_path }}/"
# rem kubelet directory - may have pod data busy
#        - "{{ kubelet_data_path }}/"
        - "{{ kuberouter_config_path }}/"
        - "{{ kuberouter_data_path }}/"         


    - debug: 
        msg: "{{ kube_config_path }}, {{etcd_config_path }}, {{ flannel_config_path }}, {{ cni_config_path }} directories removed on {{ inventory_hostname }}."


  when:
    - inventory_hostname in groups['kube-nodes']

# end block

