---

# playbook - create-kube-cluster-master.yml
#

# only use this playbook for kube cluster masters
#

- hosts: kube-masters
  become: yes
  roles:
    - { role: ../roles/create-kube-cluster-master }
