---

# playbook - create-kube-pod-network-config-in-etcd.yml
#

# func:
#
#   create kube pod network config in etcd
#   
#   key url: /kube/network/config
#   key value:
#     ref: {"Network":"172.30.0.0/16","SubnetLen":24,"Backend":{"Type":"vxlan"}}
#


- hosts: node1

# include global cluster defaults
  roles:
    - { role: ../roles/cluster-defaults }

  tasks:

#     this routine is a task in create-kube-cluster-master, we need to include its defaults
    - include_vars:
        file: ../roles/create-kube-cluster-master/defaults/main.yml

    - name: exec create kube pod network config
      include: ../roles/create-kube-cluster-master/tasks/create-kube-pod-network-config-record.yml

