---

# playbook - gen-kube-ca-cert.yml
#

# only use this playbook for node #0 of ansible-nodes

- hosts: "{{ groups['ansible-nodes'][0] }}"
  become: yes
  roles:
    - { role: ../roles/gen-kube-ca-cert }
