---

# file: gen-root-kube-etcd-ca-cert.yml

# func: 
#     (rem: need generate in sequence)
#
#   generate root ca cert
#   generate kube ca cert
#   generate etcd ca cert

# only use this playbook for node #0 of ansible-nodes

- hosts: "{{ groups['ansible-nodes'][0] }}"
  become: yes
  roles:
    - { role: ../roles/gen-root-ca-cert }

# only use this playbook for node #0 of ansible-nodes

- hosts: "{{ groups['ansible-nodes'][0] }}"
  become: yes
  roles:
    - { role: ../roles/gen-kube-ca-cert }

# only use this playbook for node #0 of ansible-nodes

- hosts: "{{ groups['ansible-nodes'][0] }}"
  become: yes
  roles:
    - { role: ../roles/gen-etcd-ca-cert }
