---

# file: remove-etcd-kube-root-ca-cert.yml

# remove all ca cert in reverse sequence as they are generated
#   remove etcd ca cert
#   remove kube ca cert
#   remove root ca cert

- hosts: "{{ groups['ansible-nodes'][0] }}"
  roles:
    - { role: ../roles/cluster-defaults }
  tasks:
#   # remove effects taken by role gen-etcd-ca-cert
#       remove /etc/cert-cache/etcd directory on remote
#       remove /etc/cert-cache/flanneld directory on remote
#       remmark: backup directory in dep-data/cert-local is not removed
#
    - name: remove procedure of role gen-etcd-ca-cert
      include: ../roles/gen-etcd-ca-cert/tasks/remove-gen-etcd-ca.yml

- hosts: "{{ groups['ansible-nodes'][0] }}"
  roles:
    - { role: ../roles/cluster-defaults }
  tasks:
#   # remove effects taken by role gen-root-ca-cert
#       remove cert-cache directory on remote
#       remove ansible temp exchange directory
#       will also remove cfssl utility on remote)
#       remove /etc/cert-cache/ca-config directory on remote
#       remove /etc/cert-cache/ca directory on remote
#       remmark: ca and ca-config directory in dep-data/cert-local is not removed
#
    - name: remove procedure of role gen-kube-ca-cert
      include: ../roles/gen-kube-ca-cert/tasks/remove-gen-kube-ca.yml

- hosts: "{{ groups['ansible-nodes'][0] }}"
  roles:
    - { role: ../roles/cluster-defaults }
  tasks:
#   # remove effects taken by role gen-root-ca-cert
#       remove cert-cache directory on remote
#       remove ansible temp exchange directory
#       will also remove cfssl utility on remote)
#       remove /etc/cert-cache/ca-config directory on remote
#       remove /etc/cert-cache/ca directory on remote
#       remmark: ca and ca-config directory in dep-data/cert-local is not removed
#
    - name: remove procedure of role gen-root-ca-cert
      include: ../roles/gen-root-ca-cert/tasks/remove-gen-root-ca.yml

