---

# file: deploy-kube-scheduler-service.yml
# 
# func:
#  . deploy scheduler service
#      - create scheduler parameter config file
#      - create scheduler parameter systemd unit file
#      - enable firewall rule for scheduler
#      - enable/start controller-manager service

# to check after deploy:
# 
# 1. check listen port
#    # ss -nutlp |  grep kube-scheduler
# 2. check metrics
#    # curl -s http://127.0.0.1:10251/metrics | head
# 3. check ha of scheduler cluster
#    (shutdown one node and check log on other node, if other node get leader rights)
# 4. check current leader
#    # kubectl get endpoints kube-scheduler --namespace=kube-system -o yaml


- name: exec create-kube-scheduler-config
  import_tasks: kube-core-service/scheduler/create-kube-scheduler-config.yml

- name: exec create-kube-scheduler-systemd-file
  import_tasks: kube-core-service/scheduler/create-kube-scheduler-systemd-file.yml

# enable and start kube-scheduler service
- name: enable and start kube-scheduler service
  systemd:
    name: kube-scheduler
    daemon_reload: yes
    state: restarted
    enabled: yes
