---

# file: copy-ca-cfg.yml

- name: exec copy ca-config to cert-cache
  block:
    - name: prompt exec copy ca-config to cert-cache
      debug: 
        msg: "notified -> start copy ca-config and ca-csr to remote cache ..."

#   copy ca-config, ca-csr and intermediate ca csr file from role files/ to cert-cache (ansible machine /etc/cert-cache/ca-config
    - name: copy ca-config and ca-csr (from role files/) to remote cache
      copy:
        src: "{{ item }}"
        dest: "{{ cert_cache_path_ca_config }}/"
      with_items:
        - ca-config.json
        - ca-csr.json
        - intermediate-ca-csr.json
        - root-to-intermediate-ca-config.json

#   create time stamp record
    - name: create time stamp record
      command: date
      register: date_command
    - name: log time stamp record on local
      local_action:
        copy content=date_command.stdout dest="{{ dep_path_tmp_exchange }}/timestamp.log"
    - name: push record on local to remote
      copy:
        src: "{{ dep_path_tmp_exchange }}/timestamp.log"
        dest: "{{ cert_cache_path_ca_config }}/"      

  rescue:
    - debug:
        msg: "issue in exec ca-config to cert-cache task"
  always:
    - debug:
        msg: ". exit exec copy ca-config to cert-cache (copy-ca-cfg.yml)"
