---

# file: copy-ca-cfg.yml

- name: exec_copy_ca_cfg_to_cache
  block:
    - name: prompt exec_copy_ca_cfg_to_cache notified
      debug: 
        msg: "notified -> start copy ca-config and ca-csr to remote cache ..."

    - name: copy ca-config and ca-csr to remote cache
      copy:
        src: "{{ item }}"
        dest: "{{ cert_cache_path_ca_config }}"
      with_items:
        - ca-config.json
        - ca-csr.json
#      changed_when: True
#      notify: exec_gen_ca_cert
#     listen: ca_cache_dir_created

    - name: create time stamp record
      command: date
      register: date_command
    - name: log time stamp record on local
      local_action:
        copy content="{{ date_command.stdout }}" dest="{{ dep_path_tmp_exchange }}/timestamp.log"
    - name: push record on local to remote
      copy:
        src: "{{ dep_path_tmp_exchange }}/timestamp.log"
        dest: "{{ cert_cache_path_ca_config }}"      

  rescue:
    - debug:
        msg: "issue in exec_copy_ca_cfg_to_cache"
  always:
    - debug:
        msg: ". exit copy-ca-cfg.yml"
