---

# file: roles/gen-root-ca-cert/tasks/main.yml

- name: traceing in gen-root-ca-cert/task/main.yml
  debug:
    msg: "check tracing - starting gen-root-ca-cert task main"
  run_once: true
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

- name: schedule exec generating root ca
  import_tasks: schedule-gen-root-ca.yml
  run_once: true
  delegate_to: "{{ groups['ansible-nodes'][0] }}"

